/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Food : public FoodBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallFoodBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Food.def
	// Please inherit and implement "class Food : public FoodBase"
class KBENGINEPLUGINS_API FoodBase : public Entity
{
public:
	EntityBaseEntityCall_FoodBase* pBaseEntityCall;
	EntityCellEntityCall_FoodBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	FoodBase();
	virtual ~FoodBase();

	void attachComponents() override;
	void detachComponents() override;

};

}