/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Room : public RoomBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallRoomBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/Room.def
	// Please inherit and implement "class Room : public RoomBase"
class KBENGINEPLUGINS_API RoomBase : public Entity
{
public:
	EntityBaseEntityCall_RoomBase* pBaseEntityCall;
	EntityCellEntityCall_RoomBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	RoomBase();
	virtual ~RoomBase();

	void attachComponents() override;
	void detachComponents() override;

};

}